print("______________________")
print("______________________")
print("______________________")
print("__________Barana______")
print("______________________")
print("______________________")
input("phone/id is hack accant ")
print("Accant is crack...")
input("Code ro nashan bedam ")
print("code:60903","code:50390")
print("is thank for install script")
input("is filter accant ?")
input("id/phone accant")
input("Meghdar gozaresh 1 ta 9000")
print("accant ta 24 hours filter mishe")
print("code filteri : filter filter filter 0 /Banned886297")
print("is thank you for install script")
print("script sakhte shode tavasot barana")
